data filemod6;
	infile '/folders/myfolders/sasuser.v94/MIS581/FinalOutput.csv' dlm=',' firstobs=2;
	input FIPS trump16 clinton16 otherpres16 romney12 obama12 otherpres12 demsen16 repsen16 othersen16 demhouse16 rephouse16 otherhouse16 repgov14 demgov14 white_pct black_pct hispanic_pct nonwhite_pct foreignborn_pct female_pct age29andunder_pct age65andolder_pct median_hh_inc clf_unemploy_pct lesshs_pct lesscollege_pct lesshs_whites_pct lesscollege_whites_pct rural_pct ruralurban_cc Density TotalCongregations TotalAdherents TotalAdherentsperThousand EvangelicalProtestantAdherents EvangelicalProtestantsPerThous BlackProtestantAdherents BlackProtestantsperThousand MainlineProtestantAdherents MainlineProtestantsperThousand CatholicAdherents CatholicAdherentsperThousand OrthodoxAdherents OrthodoxAdherentsperThousand MuslimsEstimated MuslimsEstimatedperThousand ConservativeJudaismAdherents ConservativeJudaismperThou OrthodoxJudaismAdherents OrthodoxJudaismperThousand ReconstructionistJudaism ReconstructionismJudaismperThou ReformJudaismAdherents ReformJudaismperThousand TotalJudaismAdherents TotalJudaismAdherentsperThousand;

 proc univariate normal plot; var clinton16;
 proc univariate normal plot; var trump16;
 proc univariate normal plot; var romney12;
 proc univariate normal plot; var obama12;

proc reg;
model clinton16 = hispanic_pct lesscollege_whites_pct rural_pct TotalAdherents TotalAdherentsperThousand EvangelicalProtestantAdherents BlackProtestantAdherents BlackProtestantsperThousand CatholicAdherents CatholicAdherentsperThousand MuslimsEstimatedperThousand OrthodoxJudaismAdherents  ReformJudaismAdherents ReformJudaismperThousand;
*hispanic_pct age29andunder_pct lesscollege_whites_pct TotalCongregations OrthodoxAdherents OrthodoxAdherentsperThousand ReformJudaismAdherents;

proc reg;
model trump16=white_pct black_pct hispanic_pct rural_pct ruralurban_cc EvangelicalProtestantAdherents OrthodoxAdherents OrthodoxAdherentsperThousand;

proc reg;
model romney12= white_pct black_pct hispanic_pct rural_pct ruralurban_cc EvangelicalProtestantAdherents OrthodoxAdherents OrthodoxAdherentsperThousand;
*female_pct TotalAdherents;

proc reg;
model obama12=hispanic_pct lesscollege_whites_pct rural_pct TotalAdherents TotalAdherentsperThousand EvangelicalProtestantAdherents BlackProtestantAdherents BlackProtestantsperThousand CatholicAdherents CatholicAdherentsperThousand MuslimsEstimatedperThousand OrthodoxJudaismAdherents  ReformJudaismAdherents ReformJudaismperThousand;
run;




